require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TestModelsController do

  # This should return the minimal set of attributes required to create a valid
  # TestModel. As you add validations to TestModel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all test_models as @test_models" do
      test_model = TestModel.create! valid_attributes
      get :index
      assigns(:test_models).should eq([test_model])
    end
  end

  describe "GET show" do
    it "assigns the requested test_model as @test_model" do
      test_model = TestModel.create! valid_attributes
      get :show, :id => test_model.id.to_s
      assigns(:test_model).should eq(test_model)
    end
  end

  describe "GET new" do
    it "assigns a new test_model as @test_model" do
      get :new
      assigns(:test_model).should be_a_new(TestModel)
    end
  end

  describe "GET edit" do
    it "assigns the requested test_model as @test_model" do
      test_model = TestModel.create! valid_attributes
      get :edit, :id => test_model.id.to_s
      assigns(:test_model).should eq(test_model)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TestModel" do
        expect {
          post :create, :test_model => valid_attributes
        }.to change(TestModel, :count).by(1)
      end

      it "assigns a newly created test_model as @test_model" do
        post :create, :test_model => valid_attributes
        assigns(:test_model).should be_a(TestModel)
        assigns(:test_model).should be_persisted
      end

      it "redirects to the created test_model" do
        post :create, :test_model => valid_attributes
        response.should redirect_to(TestModel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved test_model as @test_model" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestModel.any_instance.stub(:save).and_return(false)
        post :create, :test_model => {}
        assigns(:test_model).should be_a_new(TestModel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestModel.any_instance.stub(:save).and_return(false)
        post :create, :test_model => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested test_model" do
        test_model = TestModel.create! valid_attributes
        # Assuming there are no other test_models in the database, this
        # specifies that the TestModel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TestModel.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => test_model.id, :test_model => {'these' => 'params'}
      end

      it "assigns the requested test_model as @test_model" do
        test_model = TestModel.create! valid_attributes
        put :update, :id => test_model.id, :test_model => valid_attributes
        assigns(:test_model).should eq(test_model)
      end

      it "redirects to the test_model" do
        test_model = TestModel.create! valid_attributes
        put :update, :id => test_model.id, :test_model => valid_attributes
        response.should redirect_to(test_model)
      end
    end

    describe "with invalid params" do
      it "assigns the test_model as @test_model" do
        test_model = TestModel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestModel.any_instance.stub(:save).and_return(false)
        put :update, :id => test_model.id.to_s, :test_model => {}
        assigns(:test_model).should eq(test_model)
      end

      it "re-renders the 'edit' template" do
        test_model = TestModel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestModel.any_instance.stub(:save).and_return(false)
        put :update, :id => test_model.id.to_s, :test_model => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested test_model" do
      test_model = TestModel.create! valid_attributes
      expect {
        delete :destroy, :id => test_model.id.to_s
      }.to change(TestModel, :count).by(-1)
    end

    it "redirects to the test_models list" do
      test_model = TestModel.create! valid_attributes
      delete :destroy, :id => test_model.id.to_s
      response.should redirect_to(test_models_url)
    end
  end

end
